version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    command: npm run start:dev
    ports:
      - '3000:3000'
      - '8080:8080'
      - '5000:5000'
      - '6881:6881'
      - '5511:5511'
      - '9081:9081'
      - '7000:7000'
    environment:
      NODE_ENV: development
