version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    command: npm run start:dev
    ports:
      - '3000:3000'
      - '8080:8080'
    environment:
      NODE_ENV: development
